import type { Display } from '../electron';

export const DisplayStub = ({
  id = 1,
  bounds = { x: 0, y: 0, width: 1920, height: 1080 },
  workArea = { x: 0, y: 0, width: 1920, height: 1040 },
  scaleFactor = 1,
  rotation = 0,
  internal = true,
  monochrome = false,
  accelerometerSupport = 'unknown',
  colorDepth = 24,
  colorSpace = 'srgb',
  depthPerComponent = 8,
  detected = true,
  displayFrequency = 60,
  label = 'Primary Display',
  maximumCursorSize = { width: 32, height: 32 },
  nativeOrigin = { x: 0, y: 0 },
  size = { width: 1920, height: 1080 },
  touchSupport = 'unknown',
  workAreaSize = { width: 1920, height: 1040 },
  ...props
}: Partial<Display> = {}): Display => ({
  id,
  bounds,
  workArea,
  scaleFactor,
  rotation,
  internal,
  monochrome,
  accelerometerSupport,
  colorDepth,
  colorSpace,
  depthPerComponent,
  detected,
  displayFrequency,
  label,
  maximumCursorSize,
  nativeOrigin,
  size,
  touchSupport,
  workAreaSize,
  ...props,
});
