import { GeneratorArgsStub } from '../../../contracts/generator-args/generator-args.stub';
import { specimensGenerateBroker } from './specimens-generate-broker';
import { specimensGenerateBrokerProxy } from './specimens-generate-broker.proxy';

const ROOT = '/virtual/declarations';
const IF_FOLDER_PREFIX = 'number-body-cond';
const IF_BOOLEAN_PREFIX = 'boolean-body-cond';
const IF_STRING_PREFIX = 'string-body-cond';
const IF_DIRECTORY = 'src/if/function-declaration';
const IF_ASSAYER_DIRECTORY = 'packages/syntax-repository/src/if/function-declaration';

describe('specimensGenerateBroker', () => {
  describe('one focus in one container', () => {
    it('VALID: {focus: if, container: function-declaration, depth: 0} => returns each specimen, its test, the manifest and the refusals', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT, syntaxes: ['if'] });

      const result = specimensGenerateBroker({
        declarationsRoot: ROOT,
        args: GeneratorArgsStub({ mode: 'write', focus: ['if'], container: ['function-declaration'], depth: 0 }),
      });

      expect(result).toStrictEqual({
        files: [
          {
            relPath: 'REFUSED.md',
            content: [
              '# Specimens TypeScript refused',
              '',
              "The generator does not write a specimen that TypeScript rejects, and lists it here with TypeScript's reason.",
              '',
              'None.',
              '',
            ].join('\n'),
          },
          {
            relPath: 'specimen-manifest.json',
            content: [
              '[',
              '  {',
              `    "folder": "${IF_BOOLEAN_PREFIX}-const",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/locked/${IF_BOOLEAN_PREFIX}-const/${IF_BOOLEAN_PREFIX}-const.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "const",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "locked"',
              '  },',
              '  {',
              `    "folder": "${IF_BOOLEAN_PREFIX}-external",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/undriven/${IF_BOOLEAN_PREFIX}-external/${IF_BOOLEAN_PREFIX}-external.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "external",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "undriven"',
              '  },',
              '  {',
              `    "folder": "${IF_BOOLEAN_PREFIX}-param",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/driven/${IF_BOOLEAN_PREFIX}-param/${IF_BOOLEAN_PREFIX}-param.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "param",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "driven"',
              '  },',
              '  {',
              `    "folder": "${IF_FOLDER_PREFIX}-const",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/locked/${IF_FOLDER_PREFIX}-const/${IF_FOLDER_PREFIX}-const.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "const",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "locked"',
              '  },',
              '  {',
              `    "folder": "${IF_FOLDER_PREFIX}-external",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/undriven/${IF_FOLDER_PREFIX}-external/${IF_FOLDER_PREFIX}-external.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "external",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "undriven"',
              '  },',
              '  {',
              `    "folder": "${IF_FOLDER_PREFIX}-param",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/driven/${IF_FOLDER_PREFIX}-param/${IF_FOLDER_PREFIX}-param.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "param",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "driven"',
              '  },',
              '  {',
              `    "folder": "${IF_STRING_PREFIX}-const",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/locked/${IF_STRING_PREFIX}-const/${IF_STRING_PREFIX}-const.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "const",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "locked"',
              '  },',
              '  {',
              `    "folder": "${IF_STRING_PREFIX}-external",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/undriven/${IF_STRING_PREFIX}-external/${IF_STRING_PREFIX}-external.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "external",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "undriven"',
              '  },',
              '  {',
              `    "folder": "${IF_STRING_PREFIX}-param",`,
              `    "relPath": "${IF_ASSAYER_DIRECTORY}/driven/${IF_STRING_PREFIX}-param/${IF_STRING_PREFIX}-param.ts",`,
              '    "focus": "if",',
              '    "container": "function-declaration",',
              '    "slot": "body",',
              '    "path": "cond",',
              '    "provenance": "param",',
              '    "uses": [',
              '      "if"',
              '    ],',
              '    "verdict": "driven"',
              '  }',
              ']',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/driven/${IF_BOOLEAN_PREFIX}-param/${IF_BOOLEAN_PREFIX}-param.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_BOOLEAN_PREFIX}-param', () => {`,
              "    it('VALID: {cond: param} => if then on line 23 driven; if else on line 23 driven, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/driven/${IF_BOOLEAN_PREFIX}-param/${IF_BOOLEAN_PREFIX}-param.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 23, driven: 'driven' }, { kind: 'if', arm: 'else', line: 23, driven: 'driven' }],",
              '            caseFailures: [],',
              '            lints: [],',
              '            undriven: [],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/driven/${IF_BOOLEAN_PREFIX}-param/${IF_BOOLEAN_PREFIX}-param.ts`,
            content: [
              '/**',
              ' * Specimen: if-boolean-function-declaration-body-cond-param',
              ' *',
              ' * Verdict: driven',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 23: driven',
              ' * - if else on line 23: driven',
              ' *',
              ' * Expected lint errors:',
              ' * - none',
              ' *',
              ' * Expected undriven errors:',
              ' * - none',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'export function booleanBodyCondParam(cond: boolean): string {',
              '    if (cond) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/driven/${IF_FOLDER_PREFIX}-param/${IF_FOLDER_PREFIX}-param.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_FOLDER_PREFIX}-param', () => {`,
              "    it('VALID: {cond: param} => if then on line 23 driven; if else on line 23 driven, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/driven/${IF_FOLDER_PREFIX}-param/${IF_FOLDER_PREFIX}-param.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 23, driven: 'driven' }, { kind: 'if', arm: 'else', line: 23, driven: 'driven' }],",
              '            caseFailures: [],',
              '            lints: [],',
              '            undriven: [],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/driven/${IF_FOLDER_PREFIX}-param/${IF_FOLDER_PREFIX}-param.ts`,
            content: [
              '/**',
              ' * Specimen: if-number-function-declaration-body-cond-param',
              ' *',
              ' * Verdict: driven',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 23: driven',
              ' * - if else on line 23: driven',
              ' *',
              ' * Expected lint errors:',
              ' * - none',
              ' *',
              ' * Expected undriven errors:',
              ' * - none',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'export function numberBodyCondParam(cond: number): string {',
              '    if (cond) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/driven/${IF_STRING_PREFIX}-param/${IF_STRING_PREFIX}-param.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_STRING_PREFIX}-param', () => {`,
              "    it('VALID: {cond: param} => if then on line 23 driven; if else on line 23 driven, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/driven/${IF_STRING_PREFIX}-param/${IF_STRING_PREFIX}-param.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 23, driven: 'driven' }, { kind: 'if', arm: 'else', line: 23, driven: 'driven' }],",
              '            caseFailures: [],',
              '            lints: [],',
              '            undriven: [],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/driven/${IF_STRING_PREFIX}-param/${IF_STRING_PREFIX}-param.ts`,
            content: [
              '/**',
              ' * Specimen: if-string-function-declaration-body-cond-param',
              ' *',
              ' * Verdict: driven',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 23: driven',
              ' * - if else on line 23: driven',
              ' *',
              ' * Expected lint errors:',
              ' * - none',
              ' *',
              ' * Expected undriven errors:',
              ' * - none',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'export function stringBodyCondParam(cond: string): string {',
              '    if (cond) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/locked/${IF_BOOLEAN_PREFIX}-const/${IF_BOOLEAN_PREFIX}-const.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_BOOLEAN_PREFIX}-const', () => {`,
              "    it('VALID: {cond: const} => if then on line 25 driven; if else on line 25 never run, unreachable-exit on line 28, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/locked/${IF_BOOLEAN_PREFIX}-const/${IF_BOOLEAN_PREFIX}-const.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 25, driven: 'driven' }, { kind: 'if', arm: 'else', line: 25, driven: 'never' }],",
              '            caseFailures: [],',
              "            lints: [{ rule: 'unreachable-exit', startLine: 28 }],",
              '            undriven: [],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/locked/${IF_BOOLEAN_PREFIX}-const/${IF_BOOLEAN_PREFIX}-const.ts`,
            content: [
              '/**',
              ' * Specimen: if-boolean-function-declaration-body-cond-const',
              ' *',
              ' * Verdict: locked',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 25: driven',
              ' * - if else on line 25: never',
              ' *',
              ' * Expected lint errors:',
              ' * - unreachable-exit on line 28',
              ' *',
              ' * Expected undriven errors:',
              ' * - none',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'const cond: boolean = true;',
              '',
              'export function booleanBodyCondConst(): string {',
              '    if (cond) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/locked/${IF_FOLDER_PREFIX}-const/${IF_FOLDER_PREFIX}-const.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_FOLDER_PREFIX}-const', () => {`,
              "    it('VALID: {cond: const} => if then on line 25 driven; if else on line 25 never run, unreachable-exit on line 28, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/locked/${IF_FOLDER_PREFIX}-const/${IF_FOLDER_PREFIX}-const.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 25, driven: 'driven' }, { kind: 'if', arm: 'else', line: 25, driven: 'never' }],",
              '            caseFailures: [],',
              "            lints: [{ rule: 'unreachable-exit', startLine: 28 }],",
              '            undriven: [],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/locked/${IF_FOLDER_PREFIX}-const/${IF_FOLDER_PREFIX}-const.ts`,
            content: [
              '/**',
              ' * Specimen: if-number-function-declaration-body-cond-const',
              ' *',
              ' * Verdict: locked',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 25: driven',
              ' * - if else on line 25: never',
              ' *',
              ' * Expected lint errors:',
              ' * - unreachable-exit on line 28',
              ' *',
              ' * Expected undriven errors:',
              ' * - none',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'const cond: number = 3;',
              '',
              'export function numberBodyCondConst(): string {',
              '    if (cond) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/locked/${IF_STRING_PREFIX}-const/${IF_STRING_PREFIX}-const.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_STRING_PREFIX}-const', () => {`,
              "    it('VALID: {cond: const} => if then on line 25 driven; if else on line 25 never run, unreachable-exit on line 28, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/locked/${IF_STRING_PREFIX}-const/${IF_STRING_PREFIX}-const.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 25, driven: 'driven' }, { kind: 'if', arm: 'else', line: 25, driven: 'never' }],",
              '            caseFailures: [],',
              "            lints: [{ rule: 'unreachable-exit', startLine: 28 }],",
              '            undriven: [],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/locked/${IF_STRING_PREFIX}-const/${IF_STRING_PREFIX}-const.ts`,
            content: [
              '/**',
              ' * Specimen: if-string-function-declaration-body-cond-const',
              ' *',
              ' * Verdict: locked',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 25: driven',
              ' * - if else on line 25: never',
              ' *',
              ' * Expected lint errors:',
              ' * - unreachable-exit on line 28',
              ' *',
              ' * Expected undriven errors:',
              ' * - none',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              "const cond: string = 'abc';",
              '',
              'export function stringBodyCondConst(): string {',
              '    if (cond) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/undriven/${IF_BOOLEAN_PREFIX}-external/${IF_BOOLEAN_PREFIX}-external.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_BOOLEAN_PREFIX}-external', () => {`,
              "    it('VALID: {cond: external} => if then on line 23 never run; if else on line 23 never run, undriven from line 23, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/undriven/${IF_BOOLEAN_PREFIX}-external/${IF_BOOLEAN_PREFIX}-external.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 23, driven: 'never' }, { kind: 'if', arm: 'else', line: 23, driven: 'never' }],",
              '            caseFailures: [],',
              "            lints: [],",
              '            undriven: [{ startLine: 23 }],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/undriven/${IF_BOOLEAN_PREFIX}-external/${IF_BOOLEAN_PREFIX}-external.ts`,
            content: [
              '/**',
              ' * Specimen: if-boolean-function-declaration-body-cond-external',
              ' *',
              ' * Verdict: undriven',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 23: never',
              ' * - if else on line 23: never',
              ' *',
              ' * Expected lint errors:',
              ' * - none',
              ' *',
              ' * Expected undriven errors:',
              ' * - line 23',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'export function booleanBodyCondExternal(): string {',
              "    if (process.argv[2] === 'yes') {",
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/undriven/${IF_FOLDER_PREFIX}-external/${IF_FOLDER_PREFIX}-external.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_FOLDER_PREFIX}-external', () => {`,
              "    it('VALID: {cond: external} => if then on line 23 never run; if else on line 23 never run, undriven from line 23, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/undriven/${IF_FOLDER_PREFIX}-external/${IF_FOLDER_PREFIX}-external.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 23, driven: 'never' }, { kind: 'if', arm: 'else', line: 23, driven: 'never' }],",
              '            caseFailures: [],',
              '            lints: [],',
              '            undriven: [{ startLine: 23 }],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/undriven/${IF_FOLDER_PREFIX}-external/${IF_FOLDER_PREFIX}-external.ts`,
            content: [
              '/**',
              ' * Specimen: if-number-function-declaration-body-cond-external',
              ' *',
              ' * Verdict: undriven',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 23: never',
              ' * - if else on line 23: never',
              ' *',
              ' * Expected lint errors:',
              ' * - none',
              ' *',
              ' * Expected undriven errors:',
              ' * - line 23',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'export function numberBodyCondExternal(): string {',
              '    if (Number(process.argv[2])) {',
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/undriven/${IF_STRING_PREFIX}-external/${IF_STRING_PREFIX}-external.test.ts`,
            content: [
              "import { join } from 'path';",
              '',
              "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
              '',
              `describe('${IF_STRING_PREFIX}-external', () => {`,
              "    it('VALID: {cond: external} => if then on line 23 never run; if else on line 23 never run, undriven from line 23, every case passes', async () => {",
              '        const observation = await specimenObserveBroker({',
              "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
              `            relPath: '${IF_ASSAYER_DIRECTORY}/undriven/${IF_STRING_PREFIX}-external/${IF_STRING_PREFIX}-external.ts'`,
              '        });',
              '        expect(observation).toStrictEqual({',
              "            branches: [{ kind: 'if', arm: 'then', line: 23, driven: 'never' }, { kind: 'if', arm: 'else', line: 23, driven: 'never' }],",
              '            caseFailures: [],',
              '            lints: [],',
              '            undriven: [{ startLine: 23 }],',
              '            darkSpots: [],',
              '            gaps: []',
              '        });',
              '    });',
              '});',
              '',
            ].join('\n'),
          },
          {
            relPath: `${IF_DIRECTORY}/undriven/${IF_STRING_PREFIX}-external/${IF_STRING_PREFIX}-external.ts`,
            content: [
              '/**',
              ' * Specimen: if-string-function-declaration-body-cond-external',
              ' *',
              ' * Verdict: undriven',
              ' *',
              ' * Expected branches:',
              ' * - if then on line 23: never',
              ' * - if else on line 23: never',
              ' *',
              ' * Expected lint errors:',
              ' * - none',
              ' *',
              ' * Expected undriven errors:',
              ' * - line 23',
              ' *',
              ' * Expected dark spot errors:',
              ' * - none',
              ' *',
              ' * Expected gap errors:',
              ' * - none',
              ' */',
              'export function stringBodyCondExternal(): string {',
              "    if (process.argv[2] ?? '') {",
              "        return 'then';",
              '    }',
              "    return 'else';",
              '}',
              '',
            ].join('\n'),
          },
        ],
        refused: [],
        manifest: [
          {
            folder: `${IF_BOOLEAN_PREFIX}-const`,
            relPath: `${IF_ASSAYER_DIRECTORY}/locked/${IF_BOOLEAN_PREFIX}-const/${IF_BOOLEAN_PREFIX}-const.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'const',
            uses: ['if'],
            verdict: 'locked',
          },
          {
            folder: `${IF_BOOLEAN_PREFIX}-external`,
            relPath: `${IF_ASSAYER_DIRECTORY}/undriven/${IF_BOOLEAN_PREFIX}-external/${IF_BOOLEAN_PREFIX}-external.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'external',
            uses: ['if'],
            verdict: 'undriven',
          },
          {
            folder: `${IF_BOOLEAN_PREFIX}-param`,
            relPath: `${IF_ASSAYER_DIRECTORY}/driven/${IF_BOOLEAN_PREFIX}-param/${IF_BOOLEAN_PREFIX}-param.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'param',
            uses: ['if'],
            verdict: 'driven',
          },
          {
            folder: `${IF_FOLDER_PREFIX}-const`,
            relPath: `${IF_ASSAYER_DIRECTORY}/locked/${IF_FOLDER_PREFIX}-const/${IF_FOLDER_PREFIX}-const.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'const',
            uses: ['if'],
            verdict: 'locked',
          },
          {
            folder: `${IF_FOLDER_PREFIX}-external`,
            relPath: `${IF_ASSAYER_DIRECTORY}/undriven/${IF_FOLDER_PREFIX}-external/${IF_FOLDER_PREFIX}-external.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'external',
            uses: ['if'],
            verdict: 'undriven',
          },
          {
            folder: `${IF_FOLDER_PREFIX}-param`,
            relPath: `${IF_ASSAYER_DIRECTORY}/driven/${IF_FOLDER_PREFIX}-param/${IF_FOLDER_PREFIX}-param.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'param',
            uses: ['if'],
            verdict: 'driven',
          },
          {
            folder: `${IF_STRING_PREFIX}-const`,
            relPath: `${IF_ASSAYER_DIRECTORY}/locked/${IF_STRING_PREFIX}-const/${IF_STRING_PREFIX}-const.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'const',
            uses: ['if'],
            verdict: 'locked',
          },
          {
            folder: `${IF_STRING_PREFIX}-external`,
            relPath: `${IF_ASSAYER_DIRECTORY}/undriven/${IF_STRING_PREFIX}-external/${IF_STRING_PREFIX}-external.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'external',
            uses: ['if'],
            verdict: 'undriven',
          },
          {
            folder: `${IF_STRING_PREFIX}-param`,
            relPath: `${IF_ASSAYER_DIRECTORY}/driven/${IF_STRING_PREFIX}-param/${IF_STRING_PREFIX}-param.ts`,
            focus: 'if',
            container: 'function-declaration',
            slot: 'body',
            path: 'cond',
            provenance: 'param',
            uses: ['if'],
            verdict: 'driven',
          },
        ],
      });
    });
  });

  describe('a nested fill', () => {
    it('VALID: {focus: if, container: function-declaration, depth omitted} => adds the specimens whose condition is a gt or nullish node, in relPath order', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT });

      const result = specimensGenerateBroker({
        declarationsRoot: ROOT,
        args: GeneratorArgsStub({ mode: 'write', focus: ['if'], container: ['function-declaration'] }),
      });

      expect(result.files.map(({ relPath }) => relPath)).toStrictEqual([
        'REFUSED.md',
        'specimen-manifest.json',
        ...[
          `driven/${IF_BOOLEAN_PREFIX}-gt-number-value-param`,
          `driven/${IF_BOOLEAN_PREFIX}-gt-string-value-param`,
          `driven/${IF_BOOLEAN_PREFIX}-nullish-boolean-value-param`,
          `driven/${IF_BOOLEAN_PREFIX}-param`,
          `driven/${IF_FOLDER_PREFIX}-nullish-number-value-param`,
          `driven/${IF_FOLDER_PREFIX}-param`,
          `driven/${IF_STRING_PREFIX}-nullish-string-value-param`,
          `driven/${IF_STRING_PREFIX}-param`,
          `locked/${IF_BOOLEAN_PREFIX}-const`,
          `locked/${IF_BOOLEAN_PREFIX}-gt-number-value-const`,
          `locked/${IF_BOOLEAN_PREFIX}-gt-string-value-const`,
          `locked/${IF_BOOLEAN_PREFIX}-nullish-boolean-value-const`,
          `locked/${IF_FOLDER_PREFIX}-const`,
          `locked/${IF_FOLDER_PREFIX}-nullish-number-value-const`,
          `locked/${IF_STRING_PREFIX}-const`,
          `locked/${IF_STRING_PREFIX}-nullish-string-value-const`,
          `undriven/${IF_BOOLEAN_PREFIX}-external`,
          `undriven/${IF_BOOLEAN_PREFIX}-gt-number-value-external`,
          `undriven/${IF_BOOLEAN_PREFIX}-gt-string-value-external`,
          `undriven/${IF_BOOLEAN_PREFIX}-nullish-boolean-value-external`,
          `undriven/${IF_FOLDER_PREFIX}-external`,
          `undriven/${IF_FOLDER_PREFIX}-nullish-number-value-external`,
          `undriven/${IF_STRING_PREFIX}-external`,
          `undriven/${IF_STRING_PREFIX}-nullish-string-value-external`,
        ].flatMap((verdictAndFolder) => [
          `${IF_DIRECTORY}/${verdictAndFolder}/${verdictAndFolder.split('/')[1]}.test.ts`,
          `${IF_DIRECTORY}/${verdictAndFolder}/${verdictAndFolder.split('/')[1]}.ts`,
        ]),
      ]);
    });
  });

  describe('an expression focus', () => {
    it('VALID: {focus: ternary, depth: 0} => plans the statement slot and the expression slot, in relPath order', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT, scenario: 'clean' });

      const result = specimensGenerateBroker({
        declarationsRoot: ROOT,
        args: GeneratorArgsStub({ mode: 'write', focus: ['ternary'], depth: 0 }),
      });

      expect(result.files.map(({ relPath }) => relPath)).toStrictEqual([
        'REFUSED.md',
        'specimen-manifest.json',
        ...[
          'driven/boolean-body-cond-param',
          'driven/boolean-default-param-cond-param',
          'driven/number-body-cond-param',
          'driven/number-default-param-cond-param',
          'driven/string-body-cond-param',
          'driven/string-default-param-cond-param',
          'locked/boolean-body-cond-const',
          'locked/boolean-default-param-cond-const',
          'locked/number-body-cond-const',
          'locked/number-default-param-cond-const',
          'locked/string-body-cond-const',
          'locked/string-default-param-cond-const',
          'undriven/boolean-body-cond-external',
          'undriven/boolean-default-param-cond-external',
          'undriven/number-body-cond-external',
          'undriven/number-default-param-cond-external',
          'undriven/string-body-cond-external',
          'undriven/string-default-param-cond-external',
        ].flatMap((verdictAndFolder) => [
          `src/ternary/function-declaration/${verdictAndFolder}/${verdictAndFolder.split('/')[1]}.test.ts`,
          `src/ternary/function-declaration/${verdictAndFolder}/${verdictAndFolder.split('/')[1]}.ts`,
        ]),
      ]);
    });

    it('VALID: {focus: ternary, slot: default-param, provenance: param} => writes the ternary as the parameter default, and a test that expects it driven both ways', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT });

      const result = specimensGenerateBroker({
        declarationsRoot: ROOT,
        args: GeneratorArgsStub({ mode: 'write', focus: ['ternary'], depth: 0 }),
      });

      expect(
        result.files.filter(({ relPath }) => relPath.includes('number-default-param-cond-param')),
      ).toStrictEqual([
        {
          relPath:
            'src/ternary/function-declaration/driven/number-default-param-cond-param/number-default-param-cond-param.test.ts',
          content: [
            "import { join } from 'path';",
            '',
            "import { specimenObserveBroker } from '@assayer/specimen-generator/observe';",
            '',
            "describe('number-default-param-cond-param', () => {",
            "    it('VALID: {cond: param} => ternary then on line 22 driven; ternary else on line 22 driven, every case passes', async () => {",
            '        const observation = await specimenObserveBroker({',
            "            repoRoot: join(__dirname, '..', '..', '..', '..', '..', '..', '..'),",
            "            relPath: 'packages/syntax-repository/src/ternary/function-declaration/driven/number-default-param-cond-param/number-default-param-cond-param.ts'",
            '        });',
            '        expect(observation).toStrictEqual({',
            "            branches: [{ kind: 'ternary', arm: 'then', line: 22, driven: 'driven' }, { kind: 'ternary', arm: 'else', line: 22, driven: 'driven' }],",
            '            caseFailures: [],',
            '            lints: [],',
            '            undriven: [],',
            '            darkSpots: [],',
            '            gaps: []',
            '        });',
            '    });',
            '});',
            '',
          ].join('\n'),
        },
        {
          relPath:
            'src/ternary/function-declaration/driven/number-default-param-cond-param/number-default-param-cond-param.ts',
          content: [
            '/**',
            ' * Specimen: ternary-number-function-declaration-default-param-cond-param',
            ' *',
            ' * Verdict: driven',
            ' *',
            ' * Expected branches:',
            ' * - ternary then on line 22: driven',
            ' * - ternary else on line 22: driven',
            ' *',
            ' * Expected lint errors:',
            ' * - none',
            ' *',
            ' * Expected undriven errors:',
            ' * - none',
            ' *',
            ' * Expected dark spot errors:',
            ' * - none',
            ' *',
            ' * Expected gap errors:',
            ' * - none',
            ' */',
            "export function numberDefaultParamCondParam(cond: number, label: string = cond ? 'then' : 'else'): string {",
            '    return label;',
            '}',
            '',
          ].join('\n'),
        },
      ]);
    });
  });

  describe('a specimen TypeScript rejects', () => {
    it('VALID: {container: unused-local} => lists each specimen as refused with its reason, and writes only the manifest and the refusals', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT, scenario: 'refusing' });

      const result = specimensGenerateBroker({
        declarationsRoot: ROOT,
        args: GeneratorArgsStub({ mode: 'write', focus: ['if'], container: ['unused-local'], depth: 0 }),
      });

      expect(result).toStrictEqual({
        files: [
          {
            relPath: 'REFUSED.md',
            content: [
              '# Specimens TypeScript refused',
              '',
              "The generator does not write a specimen that TypeScript rejects, and lists it here with TypeScript's reason.",
              '',
              "- `boolean-cond-const`: 'unused' is declared but its value is never read.",
              "- `boolean-cond-external`: 'unused' is declared but its value is never read.",
              "- `boolean-cond-param`: 'unused' is declared but its value is never read.",
              "- `number-cond-const`: 'unused' is declared but its value is never read.",
              "- `number-cond-external`: 'unused' is declared but its value is never read.",
              "- `number-cond-param`: 'unused' is declared but its value is never read.",
              "- `string-cond-const`: 'unused' is declared but its value is never read.",
              "- `string-cond-external`: 'unused' is declared but its value is never read.",
              "- `string-cond-param`: 'unused' is declared but its value is never read.",
              '',
            ].join('\n'),
          },
          { relPath: 'specimen-manifest.json', content: '[]\n' },
        ],
        refused: [
          {
            folder: 'boolean-cond-const',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'boolean-cond-external',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'boolean-cond-param',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'number-cond-const',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'number-cond-external',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'number-cond-param',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'string-cond-const',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'string-cond-external',
            reason: "'unused' is declared but its value is never read.",
          },
          {
            folder: 'string-cond-param',
            reason: "'unused' is declared but its value is never read.",
          },
        ],
        manifest: [],
      });
    });

    it('VALID: {focus: if, every container} => keeps the clean container and refuses the other, and each list stays sorted', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT, scenario: 'refusing' });

      const result = specimensGenerateBroker({
        declarationsRoot: ROOT,
        args: GeneratorArgsStub({ mode: 'write', focus: ['if'], depth: 0 }),
      });

      expect({
        refused: result.refused.map(({ folder }) => folder),
        manifest: result.manifest.map(({ folder }) => folder),
      }).toStrictEqual({
        refused: [
          'boolean-cond-const',
          'boolean-cond-external',
          'boolean-cond-param',
          'number-cond-const',
          'number-cond-external',
          'number-cond-param',
          'string-cond-const',
          'string-cond-external',
          'string-cond-param',
        ],
        manifest: [
          'boolean-body-cond-const',
          'boolean-body-cond-external',
          'boolean-body-cond-param',
          'number-body-cond-const',
          'number-body-cond-external',
          'number-body-cond-param',
          'string-body-cond-const',
          'string-body-cond-external',
          'string-body-cond-param',
        ],
      });
    });
  });

  describe('names the generator does not know', () => {
    it('ERROR: {focus: [nope]} => throws naming the focus and the known names', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT });

      expect(() =>
        specimensGenerateBroker({ declarationsRoot: ROOT, args: GeneratorArgsStub({ focus: ['nope'] }) }),
      ).toThrow(
        /^The focus 'nope' matches no syntax or shim declaration\. The known names are: gt, if, nullish, ternary\. Name one of them, or add declarations\/syntax\/nope\.syntax\.ts\.$/u,
      );
    });

    it('ERROR: {container: [nope]} => throws naming the container and the known names', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT });

      expect(() =>
        specimensGenerateBroker({
          declarationsRoot: ROOT,
          args: GeneratorArgsStub({ focus: ['if'], container: ['nope'] }),
        }),
      ).toThrow(
        /^The container 'nope' matches no container declaration\. The known names are: function-declaration\. Name one of them, or add declarations\/containers\/nope\.container\.ts\.$/u,
      );
    });
  });

  describe('two specimens with one path', () => {
    it('ERROR: {slots that produce the same path} => throws naming each shared path', () => {
      const proxy = specimensGenerateBrokerProxy();
      proxy.setupTree({ declarationsRoot: ROOT, scenario: 'colliding' });

      expect(() =>
        specimensGenerateBroker({ declarationsRoot: ROOT, args: GeneratorArgsStub({ focus: ['if'], depth: 0 }) }),
      ).toThrow(
        /^Two specimens share one path: src\/if\/x\/driven\/boolean-y-z-cond-param\/boolean-y-z-cond-param\.ts, src\/if\/x\/driven\/number-y-z-cond-param\/number-y-z-cond-param\.ts, src\/if\/x\/driven\/string-y-z-cond-param\/string-y-z-cond-param\.ts, src\/if\/x\/locked\/boolean-y-z-cond-const\/boolean-y-z-cond-const\.ts, src\/if\/x\/locked\/number-y-z-cond-const\/number-y-z-cond-const\.ts, src\/if\/x\/locked\/string-y-z-cond-const\/string-y-z-cond-const\.ts, src\/if\/x\/undriven\/boolean-y-z-cond-external\/boolean-y-z-cond-external\.ts, src\/if\/x\/undriven\/number-y-z-cond-external\/number-y-z-cond-external\.ts, src\/if\/x\/undriven\/string-y-z-cond-external\/string-y-z-cond-external\.ts\. Rename a container, slot or hole so the names differ, because the folder name is built from them\.$/u,
      );
    });
  });
});
