/**
 * PURPOSE: The `typescript` subpath of the npm gateway. Every name here is the TypeScript compiler
 * that `ts-morph` bundles, `require('ts-morph').ts`, never the npm `typescript` package. So the walk,
 * module resolution, the tsconfig read and harness loading all run on one compiler, whose version
 * Assayer's own `ts-morph` fixes. The npm `typescript` package is only a peer dependency, for ts-jest.
 *
 * The default export is that compiler object. Each named export comes from
 * `bundled-typescript/bundled-typescript.ts`, which lifts the members callers use off the namespace.
 * A caller that reaches for a member missing here fails typecheck (TS2305 or TS2339). Add the name to
 * both lists.
 *
 * Two jobs are wrappers, not pass-throughs, because each reads the real disk through `ts.sys`:
 * `resolveModuleFile` resolves a module specifier, and `readNearestTsconfig` finds and reads a
 * tsconfig. Each has a proxy a test can stage.
 *
 * USAGE:
 * import ts from '#gateway/npm/typescript';
 * // ts is require('ts-morph').ts; typescript.test.ts proves it is the same object
 */

export { ts as default } from 'ts-morph';
export { readNearestTsconfig } from './read-nearest-tsconfig/read-nearest-tsconfig';
export { resolveModuleFile } from './resolve-module-file/resolve-module-file';
export {
  EmitHint,
  ModuleKind,
  ModuleResolutionKind,
  ScriptKind,
  ScriptTarget,
  SyntaxKind,
  TypeFlags,
  addSyntheticLeadingComment,
  canHaveModifiers,
  createCompilerHost,
  createPrinter,
  createProgram,
  createSourceFile,
  factory,
  findConfigFile,
  flattenDiagnosticMessageText,
  forEachChild,
  getModifiers,
  getParsedCommandLineOfConfigFile,
  isArrayLiteralExpression,
  isArrowFunction,
  isAwaitExpression,
  isBinaryExpression,
  isBindingElement,
  isBlock,
  isCallExpression,
  isClassDeclaration,
  isConditionalExpression,
  isDoStatement,
  isElementAccessExpression,
  isEnumDeclaration,
  isExportAssignment,
  isExportDeclaration,
  isExpression,
  isExpressionStatement,
  isForInStatement,
  isForOfStatement,
  isForStatement,
  isFunctionDeclaration,
  isFunctionExpression,
  isFunctionTypeNode,
  isIdentifier,
  isIfStatement,
  isImportDeclaration,
  isInterfaceDeclaration,
  isIntersectionTypeNode,
  isMethodSignature,
  isNamedExports,
  isNamedImports,
  isNamespaceExport,
  isNamespaceImport,
  isNewExpression,
  isNonNullExpression,
  isNumericLiteral,
  isObjectLiteralExpression,
  isParameter,
  isParenthesizedExpression,
  isParenthesizedTypeNode,
  isPropertyAccessExpression,
  isPropertyAssignment,
  isPropertySignature,
  isQualifiedName,
  isRegularExpressionLiteral,
  isReturnStatement,
  isShorthandPropertyAssignment,
  isSourceFile,
  isSpreadAssignment,
  isStatement,
  isStringLiteral,
  isSwitchStatement,
  isTryStatement,
  isTypeAliasDeclaration,
  isTypeLiteralNode,
  isTypeNode,
  isTypeParameterDeclaration,
  isTypeQueryNode,
  isTypeReferenceNode,
  isVariableDeclaration,
  isVariableStatement,
  isWhileStatement,
  parseConfigFileTextToJson,
  parseJsonConfigFileContent,
  parseJsonText,
  readConfigFile,
  readJsonConfigFile,
  resolveModuleName,
  sys,
  transform,
  transpileModule,
  visitEachChild,
} from './bundled-typescript/bundled-typescript';
export type {
  BindingName,
  CompilerOptions,
  ConciseBody,
  Diagnostic,
  ExportDeclaration,
  Expression,
  Identifier,
  ImportDeclaration,
  InterfaceDeclaration,
  MemberName,
  Node,
  NodeFactory,
  ObjectLiteralElementLike,
  ParameterDeclaration,
  ParseConfigFileHost,
  Program,
  PropertyName,
  ResolvedModuleWithFailedLookupLocations,
  SourceFile,
  Statement,
  TransformationContext,
  Type,
  TypeAliasDeclaration,
  TypeReference,
  VariableStatement,
} from './bundled-typescript/bundled-typescript';
