/**
 * PURPOSE: Generates the trivial shim Jest discovers for one file's case set.
 *
 *   It is deliberately almost empty. Assayer's execution model is that runners consume case DATA at
 *   runtime — there are no emitted `.test.ts` files, because those would be a second source of truth
 *   that drifts and tempts hand-editing. A shim exists only because Jest needs a discoverable file,
 *   so it contains no expectations, no logic, and nothing worth reading: it requires the case set and
 *   hands each case to the interpreter.
 *
 *   It writes results in `afterAll` so a FAILING case still records its trace — the failure is
 *   exactly when the trace matters most.
 *
 * USAGE:
 * assembleShimTransformer({ caseSetPath, adaptersPath, resultPath, runId });
 * // Returns the shim's JavaScript source
 */
import { shimSourceContract } from '../../contracts/shim-source/shim-source-contract';
import type { ShimSource } from '../../contracts/shim-source/shim-source-contract';

export const assembleShimTransformer = ({
  caseSetPath,
  adaptersPath,
  resultPath,
  runId,
}: {
  caseSetPath: string;
  adaptersPath: string;
  resultPath: string;
  runId: string;
}): ShimSource =>
  shimSourceContract.parse(
    [
      '// GENERATED by Assayer. Cache-resident, never committed, never edited.',
      '// It exists only so Jest has a discoverable file; the cases are DATA, not code.',
      `const { jestInterpretCaseAdapter, jestResolveEntryAdapter } = require(${JSON.stringify(adaptersPath)});`,
      "const { mkdirSync, writeFileSync } = require('node:fs');",
      "const { dirname } = require('node:path');",
      `const caseSet = require(${JSON.stringify(caseSetPath)});`,
      'const subject = require(caseSet.modulePath);',
      'const cases = [];',
      '',
      'describe(caseSet.relPath, () => {',
      '  for (const entry of caseSet.entries) {',
      '    for (const [index, testCase] of entry.cases.entries()) {',
      // Concatenated rather than a template literal: a `${}` inside this plain string would be read
      // as an interpolation of THIS file, not of the shim.
      "      it(entry.name + ' case ' + index, () => {",
      '        const result = jestInterpretCaseAdapter({',
      // Resolved per ACCESS and per case: a method needs a fresh instance, and reading
      // subject[entry.name] would find nothing for one.
      '          entry: jestResolveEntryAdapter({ subject, name: entry.name, access: entry.access }),',
      '          entryName: entry.name,',
      '          exitIds: entry.exitIds,',
      '          testCase,',
      '          probe: globalThis.__P,',
      '        });',
      '        cases.push(result);',
      "        expect(result.status).toBe('passed');",
      '      });',
      '    }',
      '  }',
      '});',
      '',
      '// afterAll, not per-case: a FAILING case must still record its trace, which is when it matters.',
      'afterAll(() => {',
      `  mkdirSync(dirname(${JSON.stringify(resultPath)}), { recursive: true });`,
      `  writeFileSync(${JSON.stringify(resultPath)}, JSON.stringify({`,
      `    runId: ${JSON.stringify(runId)},`,
      '    relPath: caseSet.relPath,',
      '    cases,',
      // Carried through, not recomputed: a gap is what Assayer could NOT drive, and a run that
      // reports only its passes reads as complete coverage of the file.
      '    gaps: caseSet.gaps,',
      '  }, null, 2));',
      '});',
      '',
    ].join('\n'),
  );
