/**
 * PURPOSE: Generates the trivial shim Jest discovers for one file's case set, in the module format the
 *   file itself runs in.
 *
 *   It is deliberately almost empty. Assayer's execution model is that runners consume case DATA at
 *   runtime — there are no emitted `.test.ts` files, because those would be a second source of truth
 *   that drifts and tempts hand-editing. A shim exists only because Jest needs a discoverable file,
 *   so it contains no expectations, no logic, and nothing worth reading: it loads the case set and
 *   hands each case to the interpreter.
 *
 *   `format` picks how it loads things. A `commonjs` shim is CommonJS and `require`s. An `esm` shim is an
 *   ES module and `await import()`s, because Jest refuses to `require` a file it loads as an ES module.
 *   An ESM shim also installs the `__P` probe runtime itself, before it loads the subject, because an
 *   ESM run has no setup file to do it. It reads the `jest` object off `import.meta.jest`, where Jest
 *   puts it for an ES module. The rest of the two shims is the same text.
 *
 *   It writes results in `afterAll` so a FAILING case still records its trace — the failure is
 *   exactly when the trace matters most.
 *
 *   `requireFresh` is the one thing it does that the interpreter cannot. A module scope's body runs
 *   once per load, so driving it a second time with different inputs means loading it a second time —
 *   and the module registry belongs to the file Jest is running, which is this one. Resetting it is
 *   Assayer's own machinery, not a control anyone is offered: no config, harness, or case can reach
 *   it, and every file gets the same shim whether or not it has a module entry to use it. In an ESM
 *   shim it returns the import's promise, and the interpreter awaits a module entry's load.
 *
 *   LOADING IS THE READ for a harness too. When the case set names one, its colocated `.harness.ts` is
 *   loaded here — through the same ts-jest transform the subject goes through, so a harness is compiled
 *   exactly as any other TypeScript in the run — and the module body's `assayerHarness` call registers
 *   into the run-side registrar Jest maps `@assayer/core` to. The shim first hands the registrar core's
 *   main module, whose published `assayerHarness` the registrar validates with. The declarations it collected are then handed to every
 *   case. It happens once, at the top: the values are the same for every case, and re-loading a file
 *   whose only act is registration would register it again.
 *
 * USAGE:
 * assembleShimTransformer({ format: 'esm', caseSetPath, interpretCaseModule, resolveEntryModule, probeRuntimeModule, harnessModule, registrarPath, resultPath, runId });
 * // Returns the shim's JavaScript source
 */
import type { coreRuntimeStatics } from '../../statics/core-runtime/core-runtime-statics';

export const assembleShimTransformer = ({
  format,
  caseSetPath,
  interpretCaseModule,
  resolveEntryModule,
  probeRuntimeModule,
  harnessModule,
  registrarPath,
  resultPath,
  runId,
}: {
  format: (typeof coreRuntimeStatics.moduleFormats)[number];
  caseSetPath: string;
  interpretCaseModule: string;
  resolveEntryModule: string;
  probeRuntimeModule: string;
  harnessModule: string;
  registrarPath: string;
  resultPath: string;
  runId: string;
}): string =>
  [
    '// GENERATED by Assayer. Cache-resident, never committed, never edited.',
    '// It exists only so Jest has a discoverable file; the cases are DATA, not code.',
    ...(format === 'esm'
      ? [
          "import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';",
          "import { dirname } from 'node:path';",
          'const jest = import.meta.jest;',
          // Installed before the subject loads: a module scope's branches fire at LOAD time.
          `const { probeRuntimeCreateBroker } = await import(${JSON.stringify(probeRuntimeModule)});`,
          'globalThis.__P = probeRuntimeCreateBroker();',
          `const { caseInterpretBroker } = await import(${JSON.stringify(interpretCaseModule)});`,
          `const { caseResolveEntryBroker } = await import(${JSON.stringify(resolveEntryModule)});`,
          `const harnessRegistrar = await import(${JSON.stringify(registrarPath)});`,
          `const caseSet = JSON.parse(readFileSync(${JSON.stringify(caseSetPath)}, 'utf8'));`,
          'const subject = await import(caseSet.modulePath);',
          // Loading IS the read: the harness registers by being run, into the registrar Jest maps
          // `@assayer/core` to, which validates through the published module handed to it first. Named
          // only when a case reaches for a supplied input, so a file with no harness loads nothing extra.
          'if (caseSet.harnessPath !== undefined) {',
          `  harnessRegistrar.bindValidator(await import(${JSON.stringify(harnessModule)}));`,
          '  await import(caseSet.harnessPath);',
          '}',
          // Re-imports the module under whatever the case arranged, which is the only way to run a
          // module scope's body again. The registry reset is Jest's, and only a file Jest is running can
          // ask for it — which is why this cannot live in the interpreter.
          'const requireFresh = () => { jest.resetModules(); return import(caseSet.modulePath); };',
        ]
      : [
          `const { caseInterpretBroker } = require(${JSON.stringify(interpretCaseModule)});`,
          `const { caseResolveEntryBroker } = require(${JSON.stringify(resolveEntryModule)});`,
          `const harnessRegistrar = require(${JSON.stringify(registrarPath)});`,
          "const { mkdirSync, writeFileSync } = require('node:fs');",
          "const { dirname } = require('node:path');",
          `const caseSet = require(${JSON.stringify(caseSetPath)});`,
          'const subject = require(caseSet.modulePath);',
          'if (caseSet.harnessPath !== undefined) {',
          `  harnessRegistrar.bindValidator(require(${JSON.stringify(harnessModule)}));`,
          '  require(caseSet.harnessPath);',
          '}',
          'const requireFresh = () => { jest.resetModules(); return require(caseSet.modulePath); };',
        ]),
    'const cases = [];',
    '',
    'describe(caseSet.relPath, () => {',
    '  for (const entry of caseSet.entries) {',
    '    for (const [index, testCase] of entry.cases.entries()) {',
    // Concatenated rather than a template literal: a `${}` inside this plain string would be read
    // as an interpolation of THIS file, not of the shim.
    "      it(entry.name + ' case ' + index, async () => {",
    '        const result = await caseInterpretBroker({',
    // Resolved per ACCESS and per case: a method needs a fresh instance, reading
    // subject[entry.name] would find nothing for one, and a module scope is no property at all.
    '          entry: caseResolveEntryBroker({ subject, name: entry.name, access: entry.access, requireFresh }),',
    '          entryName: entry.name,',
    // The access tells the interpreter a module entry's load is what it awaits.
    '          access: entry.access,',
    '          exitIds: entry.exitIds,',
    '          testCase,',
    '          probe: globalThis.__P,',
    // What the harness file registered when it ran above. Handed to every case, since a declaration is
    // the file's, not any one case's.
    '          harness: harnessRegistrar.declarations,',
    '        });',
    '        cases.push(result);',
    "        expect(result.status).toBe('passed');",
    '      });',
    '    }',
    '  }',
    '});',
    '',
    '// afterAll, not per-case: a FAILING case must still record its trace, which is when it matters.',
    'afterAll(() => {',
    `  mkdirSync(dirname(${JSON.stringify(resultPath)}), { recursive: true });`,
    `  writeFileSync(${JSON.stringify(resultPath)}, JSON.stringify({`,
    `    runId: ${JSON.stringify(runId)},`,
    '    relPath: caseSet.relPath,',
    '    cases,',
    // Carried through, not recomputed: a gap is what Assayer could NOT drive, and a run that
    // reports only its passes reads as complete coverage of the file.
    '    gaps: caseSet.gaps,',
    // Beside the gaps, never merged into them: a dark spot is syntax Assayer never understood, so
    // it is Assayer's debt rather than a harness the reader owes.
    '    darkSpots: caseSet.darkSpots,',
    // The third channel, beside both: logic Assayer read perfectly and never drove. No harness
    // closes it and the analyzer was not blind to it, so neither of the other two may absorb it.
    '    undriven: caseSet.undriven,',
    // The fourth: patterns the repo should change (dead surface). Carried so the responder can fail
    // the run on them when the repo asked, exactly as it does for a dark spot.
    '    lints: caseSet.lints,',
    '  }, null, 2));',
    '});',
    '',
  ].join('\n');
