import { assembleShimTransformer } from './assemble-shim-transformer';

// Asserted whole rather than by fragments: this is the ONLY code Assayer generates, and the design
// rests on it staying worthless to read — no expectations of its own beyond the interpreter's
// verdict, no logic, nothing anyone would be tempted to hand-edit. A golden string is what makes
// "the shim grew a brain" impossible to land unnoticed.
const EXPECTED = [
  '// GENERATED by Assayer. Cache-resident, never committed, never edited.',
  '// It exists only so Jest has a discoverable file; the cases are DATA, not code.',
  'const { jestInterpretCaseAdapter } = require("/core/dist/adapters");',
  "const { mkdirSync, writeFileSync } = require('node:fs');",
  "const { dirname } = require('node:path');",
  'const caseSet = require("/cache/runs/r1/0.cases.json");',
  'const subject = require(caseSet.modulePath);',
  'const cases = [];',
  '',
  'describe(caseSet.relPath, () => {',
  '  for (const entry of caseSet.entries) {',
  '    for (const [index, testCase] of entry.cases.entries()) {',
  "      it(entry.name + ' case ' + index, () => {",
  '        const result = jestInterpretCaseAdapter({',
  '          entry: subject[entry.name],',
  '          entryName: entry.name,',
  '          exitIds: entry.exitIds,',
  '          testCase,',
  '          probe: globalThis.__P,',
  '        });',
  '        cases.push(result);',
  "        expect(result.status).toBe('passed');",
  '      });',
  '    }',
  '  }',
  '});',
  '',
  '// afterAll, not per-case: a FAILING case must still record its trace, which is when it matters.',
  'afterAll(() => {',
  '  mkdirSync(dirname("/cache/runs/r1/run.json"), { recursive: true });',
  '  writeFileSync("/cache/runs/r1/run.json", JSON.stringify({',
  '    runId: "r1",',
  '    relPath: caseSet.relPath,',
  '    cases,',
  '  }, null, 2));',
  '});',
  '',
].join('\n');

describe('assembleShimTransformer', () => {
  describe('the shim it generates', () => {
    it('VALID: {paths and a runId} => the exact shim, requiring the case set and interpreter by absolute path', () => {
      expect(
        assembleShimTransformer({
          caseSetPath: '/cache/runs/r1/0.cases.json',
          adaptersPath: '/core/dist/adapters',
          resultPath: '/cache/runs/r1/run.json',
          runId: 'r1',
        }),
      ).toBe(EXPECTED);
    });

    // Paths are JSON-encoded rather than interpolated, so a Windows path's backslashes cannot turn
    // into escape sequences in the emitted require().
    it('EDGE: {a path containing backslashes} => encoded, not interpolated raw', () => {
      const shim = assembleShimTransformer({
        caseSetPath: 'C:\\cache\\0.cases.json',
        adaptersPath: '/core/dist/adapters',
        resultPath: '/cache/run.json',
        runId: 'r1',
      });

      expect(shim.split('\n')[5]).toBe('const caseSet = require("C:\\\\cache\\\\0.cases.json");');
    });
  });
});
