import { assembleShimTransformer } from './assemble-shim-transformer';

// Asserted whole rather than by fragments: this is the ONLY code Assayer generates, and the design
// rests on it staying worthless to read — no expectations of its own beyond the interpreter's
// verdict, no logic, nothing anyone would be tempted to hand-edit. A golden string is what makes
// "the shim grew a brain" impossible to land unnoticed.
const BODY = [
  'const cases = [];',
  '',
  'describe(caseSet.relPath, () => {',
  '  for (const entry of caseSet.entries) {',
  '    for (const [index, testCase] of entry.cases.entries()) {',
  "      it(entry.name + ' case ' + index, async () => {",
  '        const result = await caseInterpretBroker({',
  '          entry: caseResolveEntryBroker({ subject, name: entry.name, access: entry.access, requireFresh, construct: entry.construct }),',
  '          entryName: entry.name,',
  '          exitIds: entry.exitIds,',
  '          testCase,',
  '          probe: globalThis.__P,',
  '          harness: harnessRegistrar.declarations,',
  '        });',
  '        cases.push(result);',
  "        expect(result.status).toBe('passed');",
  '      });',
  '    }',
  '  }',
  '});',
  '',
  '// afterAll, not per-case: a FAILING case must still record its trace, which is when it matters.',
  'afterAll(() => {',
  '  mkdirSync(dirname("/cache/runs/r1/run.json"), { recursive: true });',
  '  writeFileSync("/cache/runs/r1/run.json", JSON.stringify({',
  '    runId: "r1",',
  '    relPath: caseSet.relPath,',
  '    cases,',
  '    gaps: caseSet.gaps,',
  '    darkSpots: caseSet.darkSpots,',
  '    undriven: caseSet.undriven,',
  '    lints: caseSet.lints,',
  '  }, null, 2));',
  '});',
  '',
];

const EXPECTED_COMMONJS = [
  '// GENERATED by Assayer. Cache-resident, never committed, never edited.',
  '// It exists only so Jest has a discoverable file; the cases are DATA, not code.',
  'const { caseInterpretBroker } = require("/core/src/brokers/case/interpret/case-interpret-broker");',
  'const { caseResolveEntryBroker } = require("/core/src/brokers/case/resolve-entry/case-resolve-entry-broker");',
  'const harnessRegistrar = require("/core/harness-registrar.js");',
  "const { mkdirSync, writeFileSync } = require('node:fs');",
  "const { dirname } = require('node:path');",
  'const caseSet = require("/cache/runs/r1/0.cases.json");',
  'const subject = require(caseSet.modulePath);',
  'if (caseSet.harnessPath !== undefined) {',
  '  harnessRegistrar.bindValidator(require("/core/index"));',
  '  require(caseSet.harnessPath);',
  '}',
  'const requireFresh = () => { jest.resetModules(); return require(caseSet.modulePath); };',
  ...BODY,
].join('\n');

const EXPECTED_ESM = [
  '// GENERATED by Assayer. Cache-resident, never committed, never edited.',
  '// It exists only so Jest has a discoverable file; the cases are DATA, not code.',
  "import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';",
  "import { dirname } from 'node:path';",
  'const jest = import.meta.jest;',
  'const { probeRuntimeCreateBroker } = await import("/core/src/brokers/probe-runtime/create/probe-runtime-create-broker");',
  'globalThis.__P = probeRuntimeCreateBroker();',
  'const { caseInterpretBroker } = await import("/core/src/brokers/case/interpret/case-interpret-broker");',
  'const { caseResolveEntryBroker } = await import("/core/src/brokers/case/resolve-entry/case-resolve-entry-broker");',
  'const harnessRegistrar = await import("/core/harness-registrar.js");',
  'const caseSet = JSON.parse(readFileSync("/cache/runs/r1/0.cases.json", \'utf8\'));',
  'const subject = await import(caseSet.modulePath);',
  'if (caseSet.harnessPath !== undefined) {',
  '  harnessRegistrar.bindValidator(await import("/core/index"));',
  '  await import(caseSet.harnessPath);',
  '}',
  'const requireFresh = () => { jest.resetModules(); return import(caseSet.modulePath); };',
  ...BODY,
].join('\n');

describe('assembleShimTransformer', () => {
  describe('the shim it generates', () => {
    it('VALID: {format: commonjs} => the exact CommonJS shim, requiring the case set and the run-time modules by absolute path', () => {
      expect(
        assembleShimTransformer({
          format: 'commonjs',
          caseSetPath: '/cache/runs/r1/0.cases.json',
          interpretCaseModule: '/core/src/brokers/case/interpret/case-interpret-broker',
          resolveEntryModule: '/core/src/brokers/case/resolve-entry/case-resolve-entry-broker',
          probeRuntimeModule: '/core/src/brokers/probe-runtime/create/probe-runtime-create-broker',
          harnessModule: '/core/index',
          registrarPath: '/core/harness-registrar.js',
          resultPath: '/cache/runs/r1/run.json',
          runId: 'r1',
        }),
      ).toBe(EXPECTED_COMMONJS);
    });

    // An ESM run has no setup file, so the shim installs the probe runtime before the subject loads, and
    // it reads `jest` off `import.meta`, where Jest puts it for an ES module.
    it('VALID: {format: esm} => the exact ESM shim, importing everything and installing the probe runtime first', () => {
      expect(
        assembleShimTransformer({
          format: 'esm',
          caseSetPath: '/cache/runs/r1/0.cases.json',
          interpretCaseModule: '/core/src/brokers/case/interpret/case-interpret-broker',
          resolveEntryModule: '/core/src/brokers/case/resolve-entry/case-resolve-entry-broker',
          probeRuntimeModule: '/core/src/brokers/probe-runtime/create/probe-runtime-create-broker',
          harnessModule: '/core/index',
          registrarPath: '/core/harness-registrar.js',
          resultPath: '/cache/runs/r1/run.json',
          runId: 'r1',
        }),
      ).toBe(EXPECTED_ESM);
    });

    // Paths are JSON-encoded rather than interpolated, so a Windows path's backslashes cannot turn
    // into escape sequences in the emitted require().
    it('EDGE: {a path containing backslashes} => encoded, not interpolated raw', () => {
      const shim = assembleShimTransformer({
        format: 'commonjs',
        caseSetPath: 'C:\\cache\\0.cases.json',
        interpretCaseModule: '/core/src/brokers/case/interpret/case-interpret-broker',
        resolveEntryModule: '/core/src/brokers/case/resolve-entry/case-resolve-entry-broker',
        probeRuntimeModule: '/core/src/brokers/probe-runtime/create/probe-runtime-create-broker',
        harnessModule: '/core/index',
        registrarPath: '/core/harness-registrar.js',
        resultPath: '/cache/run.json',
        runId: 'r1',
      });

      expect(shim.split('\n')[7]).toBe('const caseSet = require("C:\\\\cache\\\\0.cases.json");');
    });
  });
});
